version: "3.8"

services:
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: expressuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: expresspassword
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes:
      - /mongo:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge